### ISSUE TITLE
nice app

### ISSUE THREAD

**Issue by towwa** [FermiDirak/symbolic-calculus#1]

**Comment by mu578** [comment]
you should write your expression engine in scheme, closure or even common lisp then `compiling` it to JS after all JS is just another lisp for kids.

**Comment by FermiDirak** [comment]
non-issue. I coded this in Javascript because I wanted to code this in javascript. You're free to compile this code to any language using [babel.js](https://babeljs.io/).

**Comment by mu578** [comment]
Javascript by itself is not really handy for writing such tool  ; it always ends up dirty and cumbersome. For instance, writing a lisp or a scheme interpreter based on emacscript whatever family is ridiculous and useless ; doing the opposite makes sense ; it's all about efficiency, there are different animals for different purposes.
